import type { PromptPreset } from '../types/preset'

export const PRESETS: PromptPreset[] = [
  // ─── A. Render Node (Main Renderer) ───
  {
    id: 'screen-to-render',
    name: 'View to render', // 실물 Lumanova 표기 (docs/VIDEO_ANALYSIS.md 영상2 §2)
    icon: 'screen-to-render',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Create photorealistic image',
    negativePrompt: 'cartoon, illustration, sketch, low quality, blurry',
    visualConstraints: 'Preserve exact geometry, camera angle, and spatial layout from the source image.',
    forbiddenChanges: 'Do not add or remove architectural elements. Do not change room proportions.',
  },
  {
    id: 'image-to-sketch',
    name: 'Image to sketch',
    icon: 'image-to-sketch',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Convert to architectural sketch drawing',
    negativePrompt: 'photorealistic, photograph, color photo',
    visualConstraints: 'Maintain architectural proportions and perspective.',
    forbiddenChanges: 'Do not alter building geometry.',
  },
  {
    id: 'top-view',
    name: 'Top view',
    icon: 'top-view',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Generate top-down orthographic view',
    negativePrompt: 'perspective distortion, vanishing point, angled view',
    visualConstraints: "Bird's eye view, parallel projection.",
    forbiddenChanges: 'Do not add perspective.',
  },
  {
    id: 'side-view',
    name: 'Side view',
    icon: 'side-view',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Generate side elevation view',
    negativePrompt: 'top view, perspective, aerial',
    visualConstraints: 'Orthographic side elevation.',
    forbiddenChanges: 'Do not rotate the viewpoint.',
  },
  {
    id: 'another-view',
    name: 'Another view',
    icon: 'another-view',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Generate an alternative camera angle of the same scene',
    negativePrompt: 'identical angle, same viewpoint',
    visualConstraints: 'Maintain the same room, furniture, and style.',
    forbiddenChanges: 'Do not change the interior design or objects.',
  },

  // ─── B. Modifier Node (Details Editor) ───
  {
    id: 'enhance-realism',
    name: 'Enhance realism',
    icon: 'enhance-realism',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Photorealistic architectural visualization. Enhance material realism, global illumination, reflections, and micro-details. Natural lighting, physically based rendering quality.',
    negativePrompt: 'cartoon, illustration, low quality, oversaturated',
    visualConstraints: 'Preserve exact geometry, camera angle, and object placement.',
    forbiddenChanges: 'Do NOT add or remove objects. Do NOT change room layout or furniture positions.',
  },
  {
    id: 'volumetric-rays',
    name: 'Volumetric rays',
    icon: 'volumetric-rays',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add cinematic volumetric light rays. Sunlight scattering through space with realistic atmospheric particles. Soft god rays.',
    negativePrompt: 'overexposure, dramatic color shift, artificial lighting, harsh shadows',
    visualConstraints: 'Preserve all geometry and composition.',
    forbiddenChanges: 'Do NOT change lighting direction. Do NOT alter room geometry.',
  },
  {
    id: 'make-brighter',
    name: 'Make brighter',
    icon: 'make-brighter',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Increase overall exposure and brightness. Preserve color balance and material fidelity.',
    negativePrompt: 'blown highlights, overexposure, washed out, color shift',
    visualConstraints: 'Maintain original lighting direction and shadow positions.',
    forbiddenChanges: 'Do NOT change lighting direction, color temperature, or shadow geometry.',
  },
  {
    id: 'closeup',
    name: 'Closeup',
    icon: 'closeup',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Create a close-up shot of the main subject. Shallow depth of field, realistic lens compression. Focus on material detail and texture quality.',
    negativePrompt: 'wide angle, distant view, blurry subject, unfocused',
    visualConstraints: 'Maintain original style and lighting.',
    forbiddenChanges: 'Do NOT change materials or style.',
  },
  {
    id: 'axonometry',
    name: 'Axonometry',
    icon: 'axonometry',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Generate axonometric architectural visualization. Parallel projection. Clean edges, neutral lighting, technical clarity.',
    negativePrompt: 'perspective distortion, vanishing point, artistic, painterly',
    visualConstraints: 'No perspective distortion.',
    forbiddenChanges: 'Do NOT add artistic effects or stylization.',
  },
  {
    id: 'winter',
    name: 'Winter',
    icon: 'winter',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Change season to winter. Snow accumulation on horizontal surfaces. Cold daylight atmosphere. Bare trees, frost on windows.',
    negativePrompt: 'summer, green foliage, warm tones, sunny',
    visualConstraints: 'Preserve architecture and camera position.',
    forbiddenChanges: 'Do NOT change building geometry or camera angle.',
  },
  {
    id: 'autumn',
    name: 'Autumn',
    icon: 'autumn',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Change season to autumn. Warm golden and orange foliage. Soft warm-toned daylight.',
    negativePrompt: 'winter, snow, summer green, cold tones',
    visualConstraints: 'Preserve architecture and camera position.',
    forbiddenChanges: 'Do NOT change building geometry or camera angle.',
  },
  {
    id: 'technical-drawings',
    name: 'Technical drawings',
    icon: 'technical-drawings',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Architectural technical drawing style. Monochrome or limited color palette. Clear linework, no artistic shading. Orthographic or axonometric projection.',
    negativePrompt: 'photorealistic, color photo, artistic, painterly, textures',
    visualConstraints: 'Maintain exact proportions and dimensions.',
    forbiddenChanges: 'Do NOT add artistic effects. Do NOT add color beyond line weights.',
  },
  {
    id: 'logo',
    name: 'Logo',
    icon: 'logo',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Transform the image into a clean logo-style illustration. Flat colors, simplified shapes. Transparent or white background.',
    negativePrompt: 'photorealistic, textures, lighting effects, gradients, shadows',
    visualConstraints: 'Simplified geometric shapes.',
    forbiddenChanges: 'Do NOT preserve photorealistic textures.',
  },
  {
    id: 'day-to-night',
    name: 'Day to night',
    icon: 'day-to-night',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Convert daytime scene to nighttime. Artificial lighting visible from interior. Natural night sky illumination. Warm window glow.',
    negativePrompt: 'daylight, sunny, bright sky, daytime',
    visualConstraints: 'Preserve geometry and composition.',
    forbiddenChanges: 'Do NOT change building geometry or furniture.',
  },
  {
    id: 'night-to-day',
    name: 'Night to day',
    icon: 'night-to-day',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Convert nighttime scene to daytime. Natural daylight illumination. Clear or partly cloudy sky.',
    negativePrompt: 'night, dark, artificial lighting only, stars',
    visualConstraints: 'Preserve geometry and composition.',
    forbiddenChanges: 'Do NOT change building geometry or furniture.',
  },
  {
    id: 'add-people',
    name: 'Add people',
    icon: 'add-people',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add realistic people naturally integrated into the scene. Correct scale, perspective, and lighting. People should not block key architectural elements.',
    negativePrompt: 'mannequins, cartoon people, oversized, floating',
    visualConstraints: 'Match lighting and perspective of the existing scene.',
    forbiddenChanges: 'Do NOT alter architecture or furniture.',
  },
  {
    id: 'add-blurred-people',
    name: 'Add blurred people',
    icon: 'add-blurred-people',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add motion-blurred people for realism. Long exposure effect. People walking naturally through the space.',
    negativePrompt: 'sharp people, static poses, mannequins',
    visualConstraints: 'Match lighting and perspective.',
    forbiddenChanges: 'Do NOT alter architecture or furniture.',
  },
  {
    id: 'add-blurred-cars',
    name: 'Add blurred cars',
    icon: 'add-blurred-cars',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add motion-blurred cars on roads. Long exposure effect for dynamic movement.',
    negativePrompt: 'static cars, parked, sharp focus on vehicles',
    visualConstraints: 'Match road perspective and scene scale.',
    forbiddenChanges: 'Do NOT alter buildings or landscape.',
  },
  {
    id: 'add-cars',
    name: 'Add cars',
    icon: 'add-cars',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add realistic parked cars matching scene context. Correct scale and perspective.',
    negativePrompt: 'floating cars, oversized, cartoon',
    visualConstraints: 'Match lighting and perspective.',
    forbiddenChanges: 'Do NOT alter buildings.',
  },
  {
    id: 'add-flowers',
    name: 'Add flowers',
    icon: 'add-flowers',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add natural flowers subtly integrated into the scene. Respect scale, season, and climate.',
    negativePrompt: 'oversized flowers, artificial, plastic',
    visualConstraints: 'Do not obstruct architecture.',
    forbiddenChanges: 'Do NOT change architecture or major scene elements.',
  },
  {
    id: 'add-grass',
    name: 'Add grass',
    icon: 'add-grass',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add natural grass and ground cover. Realistic lawn texture, appropriate for the climate.',
    negativePrompt: 'artificial turf, oversaturated green, unrealistic',
    visualConstraints: 'Match terrain and scene context.',
    forbiddenChanges: 'Do NOT change architecture or hardscape.',
  },
  {
    id: 'add-trees',
    name: 'Add trees',
    icon: 'add-trees',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add realistic trees appropriate to the climate and scene. Correct scale and natural placement.',
    negativePrompt: 'cartoon trees, floating, oversized, indoor trees outside',
    visualConstraints: 'Match season and climate.',
    forbiddenChanges: 'Do NOT obstruct key architectural views.',
  },

  // ─── C. Upscale Node ───
  {
    id: 'upscale',
    name: 'Upscale',
    icon: 'upscale',
    category: 'upscale',
    applicableNodeTypes: ['UPSCALE'],
    mergeMode: 'replace',
    basePrompt: 'Upscale',
    negativePrompt: '',
    visualConstraints: 'Preserve all details from original.',
    forbiddenChanges: 'Do NOT alter content or composition.',
  },

  // ─── D. Video Node ───
  {
    id: 'zoom-in-video',
    name: 'Cinematic push-in',
    icon: 'zoom-in-video',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a cinematic architectural push-in shot. Slowly move the camera forward with a gentle lens-like zoom toward the main focal area. Preserve the exact room layout, furniture positions, materials, proportions, and lighting from the source image. Add only natural motion cues: subtle parallax between foreground and background, soft exposure breathing, and realistic stabilized camera movement. Do not morph objects, do not invent new furniture, and do not change the design.',
    negativePrompt: '',
    visualConstraints: 'Slow stabilized push-in with realistic architectural parallax.',
    forbiddenChanges: 'Do NOT alter geometry, furniture, materials, lighting design, or object placement.',
  },
  {
    id: 'move-forward',
    name: 'Walkthrough dolly',
    icon: 'move-forward',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Generate a refined interior walkthrough. The camera performs a slow forward dolly at eye level, moving deeper into the scene as if filmed on a gimbal. Keep all architecture, furniture, decor, openings, textures, and light sources identical to the input image. Emphasize believable spatial depth, stable perspective, gentle foreground-to-background parallax, and premium real-estate video pacing. Avoid warping, object drift, flicker, or new objects.',
    negativePrompt: '',
    visualConstraints: 'Eye-level gimbal dolly, stable perspective, natural depth.',
    forbiddenChanges: 'Do NOT change the design, add objects, remove objects, or distort straight architectural lines.',
  },
  {
    id: 'orbit',
    name: 'Hero orbit',
    icon: 'orbit',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a subtle hero orbit around the primary subject or seating area. The camera arcs gently from left to right with a controlled cinematic move, revealing depth while preserving the exact composition, room geometry, furniture, materials, and lighting. Keep vertical lines stable and avoid fisheye distortion. The motion should feel like a high-end architectural visualization shot, not a dramatic action camera move.',
    negativePrompt: '',
    visualConstraints: 'Controlled lateral arc with stable architecture and subtle parallax.',
    forbiddenChanges: 'Do NOT rotate objects, remodel the scene, or change object identities.',
  },
  {
    id: 'pan-left',
    name: 'Slow reveal pan',
    icon: 'pan-left',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Produce a slow cinematic reveal pan across the interior. Move the camera gently left with minimal shake, maintaining the original perspective and preserving every architectural detail, furniture position, texture, and light source. The motion should reveal the space naturally with soft parallax and consistent exposure. Keep the scene photorealistic and stable; no object morphing, no layout changes, no added decor.',
    negativePrompt: '',
    visualConstraints: 'Smooth lateral reveal pan with consistent exposure and no jitter.',
    forbiddenChanges: 'Do NOT change content, proportions, materials, or camera height.',
  },
  {
    id: 'cinematic-establishing',
    name: 'Cinematic establishing',
    icon: 'cinematic-establishing',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a polished cinematic establishing shot from the input image. Use a slow stabilized camera move with subtle parallax, natural exposure roll-off, gentle lens breathing, and premium film pacing. Preserve the exact subject identity, architecture, layout, object placement, materials, lighting direction, and composition. The result should feel like a high-end commercial film opening shot with realistic motion, no artificial morphing, and no new objects.',
    negativePrompt: 'fast camera, shaky handheld, warped geometry, object morphing, added objects, disappearing objects, flicker, low quality',
    visualConstraints: 'Premium cinematic opening shot, restrained motion, stable geometry.',
    forbiddenChanges: 'Do NOT change the design, identity, object positions, or camera intent.',
  },
  {
    id: 'luxury-real-estate',
    name: 'Luxury real-estate',
    icon: 'luxury-real-estate',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Generate a luxury real-estate showcase video. Move the camera slowly and smoothly through the scene with gimbal-stabilized motion, subtle foreground parallax, clean vertical lines, natural ambient light, and elegant editorial pacing. Preserve every architectural element, furniture position, material, color, and light source from the source image. Make the motion feel expensive, calm, and spatially believable.',
    negativePrompt: 'handheld shake, fisheye, warped walls, shifting furniture, extra decor, people, text, logos, flicker',
    visualConstraints: 'Architectural visualization video, stable verticals, premium property tour pacing.',
    forbiddenChanges: 'Do NOT alter floor plan, furniture, openings, built-ins, or styling.',
  },
  {
    id: 'interior-light-sweep',
    name: 'Interior light sweep',
    icon: 'interior-light-sweep',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a subtle cinematic light sweep across the interior. Keep the camera nearly locked with only minimal stabilized drift while soft natural light rolls gently over surfaces, revealing material texture, depth, reflections, and shadow detail. Preserve the exact scene geometry, composition, furniture, materials, and original lighting logic. The light motion must feel physically plausible and understated.',
    negativePrompt: 'dramatic relighting, changing sun direction, flashing, blown highlights, new lamps, object movement, material changes',
    visualConstraints: 'Near-static camera, subtle light movement, material detail emphasis.',
    forbiddenChanges: 'Do NOT redesign lighting fixtures, change materials, or move objects.',
  },
  {
    id: 'dolly-out-reveal',
    name: 'Dolly-out reveal',
    icon: 'dolly-out-reveal',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a slow cinematic dolly-out reveal. Begin close to the main subject and gently pull the camera backward to reveal more of the space while maintaining stable perspective and accurate scale. Preserve the exact composition, object identities, room geometry, furniture placement, materials, and lighting. Add only realistic parallax and lens movement, with no invented scene content.',
    negativePrompt: 'zoom snap, layout changes, new furniture, disappearing objects, stretched perspective, fisheye, flicker',
    visualConstraints: 'Smooth backward dolly, reveal more context without changing the design.',
    forbiddenChanges: 'Do NOT alter object scale, room proportions, or decor placement.',
  },
  {
    id: 'rack-focus-detail',
    name: 'Rack focus detail',
    icon: 'rack-focus-detail',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Produce a refined rack-focus detail shot. Keep the camera mostly static with a very subtle drift while focus transitions gently from the foreground detail to the main subject, revealing realistic depth of field and lens behavior. Preserve the source image composition, materials, object positions, lighting, and scene identity exactly. The motion should be quiet, photographic, and believable.',
    negativePrompt: 'object morphing, changing layout, excessive blur, focus hunting, new objects, floating artifacts, flicker',
    visualConstraints: 'Subtle depth-of-field focus transition with stable composition.',
    forbiddenChanges: 'Do NOT move objects or change the camera framing substantially.',
  },
  {
    id: 'product-hero-turntable',
    name: 'Product hero',
    icon: 'product-hero-turntable',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a premium product hero video from the input image. Use a controlled studio-style camera move with a subtle orbit or push-in around the main product, crisp reflections, realistic highlights, and elegant commercial pacing. Preserve the exact product design, proportions, color, material finish, branding placement if present, and background composition. Motion should emphasize form and material quality without changing the product.',
    negativePrompt: 'changed product shape, changed logo, extra text, deformed branding, unstable reflections, jitter, new props',
    visualConstraints: 'Commercial product film, precise object identity, controlled studio movement.',
    forbiddenChanges: 'Do NOT alter product geometry, colorway, logos, labels, or proportions.',
  },
  {
    id: 'fashion-editorial',
    name: 'Fashion editorial',
    icon: 'fashion-editorial',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a high-end fashion editorial motion shot. Use a slow cinematic camera drift, elegant posture-preserving motion, subtle fabric movement, refined lighting, and magazine-quality pacing. Preserve the person identity, clothing design, garment color, accessories, pose intention, background, and overall composition from the input image. Keep motion tasteful and realistic.',
    negativePrompt: 'face distortion, extra limbs, changing outfit, changing identity, unstable anatomy, jitter, low quality, new people',
    visualConstraints: 'Editorial fashion video, subtle human and fabric motion, stable identity.',
    forbiddenChanges: 'Do NOT change face, body proportions, outfit design, or accessories.',
  },
  {
    id: 'food-commercial',
    name: 'Food commercial',
    icon: 'food-commercial',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Generate an appetizing food commercial shot. Keep the camera controlled and close, with subtle steam or gloss highlights if appropriate, gentle depth-of-field motion, rich texture detail, and warm premium lighting. Preserve the exact dish, plating, ingredients, tableware, composition, and background from the input image. The video should feel like a polished restaurant advertisement.',
    negativePrompt: 'changing ingredients, melting shape, extra food, disappearing garnish, messy artifacts, text, flicker',
    visualConstraints: 'Premium food macro motion, appetizing texture, stable plating.',
    forbiddenChanges: 'Do NOT alter dish composition, ingredients, plate, or garnish layout.',
  },
  {
    id: 'social-vertical-ad',
    name: 'Social vertical ad',
    icon: 'social-vertical-ad',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a short premium social-media ad motion from the input image. Use clean cinematic movement, subtle zoom or parallax, polished lighting, and a strong visual hook in the first second. Preserve the exact subject, product, environment, colors, layout, and brand elements from the source image. Do not add captions or graphic overlays unless they already exist in the image.',
    negativePrompt: 'text overlays, stickers, changing brand, chaotic movement, jump cuts, distorted subject, low quality',
    visualConstraints: 'Short-form ad pacing, clean hook, stable subject, no added graphics.',
    forbiddenChanges: 'Do NOT add text, logos, stickers, or change existing brand elements.',
  },
  {
    id: 'dreamy-atmosphere',
    name: 'Dreamy atmosphere',
    icon: 'dreamy-atmosphere',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a dreamy atmospheric cinematic video. Use slow elegant camera movement, soft haze, gentle light bloom, subtle floating dust or atmosphere, and calm emotional pacing. Preserve the original subject, scene layout, materials, object positions, colors, and composition. The mood should become more poetic without changing the actual scene content.',
    negativePrompt: 'fantasy objects, heavy fog, overexposure, color washout, object morphing, scene redesign, flicker',
    visualConstraints: 'Soft atmospheric mood enhancement with preserved scene identity.',
    forbiddenChanges: 'Do NOT introduce new objects, change architecture, or alter subject identity.',
  },
  {
    id: 'night-neon-cinematic',
    name: 'Night neon cinematic',
    icon: 'night-neon-cinematic',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a cinematic night-neon motion treatment. Use slow stabilized camera movement, controlled neon glow, reflective highlights, subtle bloom, and moody contrast while preserving the source image subject, layout, object placement, materials, and composition. The motion should feel like a polished film trailer shot, with restrained atmosphere and stable geometry.',
    negativePrompt: 'new signs, added text, oversaturated neon, geometry warp, flicker, fast movement, changed objects',
    visualConstraints: 'Moody neon cinematic motion, restrained glow, stable scene.',
    forbiddenChanges: 'Do NOT add signage, text, new light fixtures, or change object identities.',
  },
  {
    id: 'minimal-camera-drift',
    name: 'Minimal drift',
    icon: 'minimal-camera-drift',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Generate a minimal premium camera drift. Keep the composition almost identical to the source image, adding only a very subtle stabilized motion, micro parallax, natural exposure breathing, and gentle lens realism. This should be the safest motion option: preserve all geometry, subject identity, object placement, materials, lighting, and framing with maximum fidelity.',
    negativePrompt: 'large camera move, object drift, warped lines, new objects, altered layout, flicker, motion blur artifacts',
    visualConstraints: 'Safest high-fidelity motion, near-static composition, subtle realism.',
    forbiddenChanges: 'Do NOT change anything except adding minimal believable camera motion.',
  },
  {
    id: 'end-frame-transition',
    name: 'End-frame transition',
    icon: 'end-frame-transition',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Create a smooth cinematic transition from the input image toward the provided end frame. Interpolate camera movement, lighting, and scene motion naturally while preserving object identities, layout continuity, materials, and spatial logic. The transition should feel intentional and filmic, with no sudden morphing, no object popping, and no invented elements between frames.',
    negativePrompt: 'hard cut, object popping, identity changes, geometry melting, new objects, flicker, unstable transition',
    visualConstraints: 'Smooth image-to-end-frame transition with stable scene continuity.',
    forbiddenChanges: 'Do NOT invent intermediate objects or change subject identity between frames.',
  },
]

export function getPresetsForNodeType(nodeType: string): PromptPreset[] {
  return PRESETS.filter((p) => p.applicableNodeTypes.includes(nodeType as PromptPreset['applicableNodeTypes'][number]))
}

export function getPresetById(id: string): PromptPreset | undefined {
  return PRESETS.find((p) => p.id === id)
}
